---
abstract: 'handy mixin for objects with a DB connection'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Module::Load: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Role-DBIConnection
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  Moo: '2'
  experimental: '0.032'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/MooX-Role-DBIConnection/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/MooX-Role-DBIConnection.git
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
